import {
    ArrowRight,
    SunIcon,
    Trophy,
    Truck,
    Zap,
    Car,
    RocketIcon,
    Rocket,
    Flame,
    Key,
    Mountain,
    Disc,
    Eye,
    Wrench,
    Flashlight,
} from "lucide-react"

export const categories = [
    {
        id: "SUV",
        name: "SUVs Incríveis",
        icon: <SunIcon size={24} />,
        description: "Veículos utilitários esportivos com robustez e conforto.",
    },
    {
        id: "SPORTS_CAR",
        name: "Máquinas de Velocidade",
        icon: <Trophy size={24} />,
        description:
        "Carros de alto desempenho projetados para velocidade extrema.",
    },
    {
        id: "DRIFT_CAR",
        name: "Drift Machines",
        icon: <Car size={24} />,
        description: "Carros japoneses icônicos, feitos para derrapar nas curvas.",
    },
    {
        id: "HYPERCAR",
        name: "Hiper Máquinas",
        icon: <Rocket size={24} />,
        description: "Supercarros ultra rápidos com tecnologia de ponta.",
    },
    {
        id: "RETRO_SUPER",
        name: "Super Clássicos",
        icon: <Car size={24} />,
        description: "Carros clássicos com potência e design vintage.",
    },
    {
        id: "SUPERCAR",
        name: "Supercarros",
        icon: <Flashlight size={24} />,
        description: "Potência extrema com visual impressionante.",
    },
    {
        id: "CLASSIC_MUSCLE",
        name: "Muscle Clássico",
        icon: <Flame size={24} />,
        description: "Muscle cars históricos com motores potentes.",
    },
    {
        id: "MODERN_MUSCLE",
        name: "Muscle Moderno",
        icon: <RocketIcon size={24} />,
        description: "Modelos contemporâneos que mantêm a essência Muscle.",
    },
    {
        id: "TRACK_TOY",
        name: "Brinquedos de Pista",
        icon: <Disc size={24} />,
        description: "Veículos projetados para velocidade e diversão nas pistas.",
    },
    {
        id: "OFFROAD",
        name: "Aventureiros",
        icon: <Mountain size={24} />,
        description: "Veículos preparados para trilhas e terrenos acidentados.",
    },
    {
        id: "BUGGY",
        name: "Buggy Radical",
        icon: <Truck size={24} />,
        description: "Leves, ágeis e perfeitos para terrenos arenosos.",
    },
    {
        id: "PICKUP_4X4",
        name: "Potência 4x4",
        icon: <Truck size={24} />,
        description: "Caminhonetes robustas para qualquer tipo de terreno.",
    },
    {
        id: "HOT_HATCH",
        name: "Hot Hatches",
        icon: <Zap size={24} />,
        description: "Compactos rápidos com espírito esportivo.",
    },
    {
        id: "SALON",
        name: "Sedans de Luxo",
        icon: <Car size={24} />,
        description: "Conforto e elegância com desempenho sofisticado.",
    },
    {
        id: "GT",
        name: "Gran Turismo",
        icon: <Key size={24} />,
        description: "Carros de longa distância com estilo e desempenho.",
    },
    {
        id: "RALLY",
        name: "Rally Beasts",
        icon: <Wrench size={24} />,
        description: "Projetados para resistir a terrenos adversos.",
    },
    {
        id: "CONCEPT",
        name: "Conceitos Futuristas",
        icon: <Eye size={24} />,
        description: "Protótipos que mostram o futuro da indústria automotiva.",
    },
];
